[build]
  command = "npm install && npm run build"
  publish = "out"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_ADMIN_API_URL = "https://facebook-page-bot-rdkt.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200